In [21]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv(r"C:\Users\Sabuj Some\OneDrive\Documents\Personal\Projects\Blinkit Retention, Churn & Cohort Analytics\Raw Data\blinkit_retention_churn_cohort_raw_realistic_2021_2025.csv")

In [3]:
# Check first few rows

df.head()

,customer_id,customer_name,email,phone,city,state,pincode,signup_date,customer_segment,acquisition_channel,...,coupon_code,coupon_type,first_order_flag,repeat_order_flag,days_since_previous_order,app_session_count,last_login_date,customer_status,churn_flag,churn_date
0,CUST021709,Rahul Bose,rahulbose8562@gmail.com,+91-9613303371,Noida,Uttar Pradesh,359716.0,NaN,New,Google,...,NONE,NaN,No,No,2.0,8,04/08/2023,Active,0,NaN
1,CUST000045,Kavya Das,kavyadas9226@gmail.com,+91-7718105707,Chennai,Tamil Nadu,543681.0,03/06/2023,Regular,Organic,...,NONE,NaN,Yes,No,5.0,9,17/10/2021,Active,0,NaN
2,CUST002107,Priya Bhowmik,priyabhowmik3537@gmail.com,+91-9931090623,Delhi,Delhi,621002.0,02/03/2023,New,Organic,...,WELCOME50,percentage,yes,No,1.0,1,11/10/2024,Churned,1,NaN
3,CUST006550,Rohan Mitra,rohanmitra6670@gmail.com,+91-8987626850,Pune,Maharashtra,901670.0,11/05/2021,new,Facebook,...,WELCOME50,Percentage,No,No,NaN,4,11/05/2021,Active,0,NaN
4,CUST015480,Diya Ganguly,diyaganguly3031@gmail.com,+91-9094700117,Jaipur,Rajasthan,984637.0,NaN,Regular,Organic,...,NONE,NaN,No,Yes,21.0,6,13/06/2025,Active,0,NaN

In [4]:
# bottom few rows
df.tail()

,customer_id,customer_name,email,phone,city,state,pincode,signup_date,customer_segment,acquisition_channel,...,coupon_code,coupon_type,first_order_flag,repeat_order_flag,days_since_previous_order,app_session_count,last_login_date,customer_status,churn_flag,churn_date
121195,CUST010378,Karan Sarkar,karansarkar445@gmail.com,+91-7594376734,Noida,Uttar Pradesh,906897.0,05/11/2025,new,Google,...,NONE,NaN,Yes,No,1.0,10,14/01/2025,Active,0,NaN
121196,CUST021331,Neha Patel,nehapatel2396@gmail.com,+91-7805887391,Gurgaon,Haryana,633552.0,11/04/2024,New,Google,...,FESTIVE100,FLAT,No,Yes,1.0,7,25/02/2022,Active,0,NaN
121197,CUST004978,Varun Verma,varunverma6338@gmail.com,+91-8006233750,Bengaluru,Karnataka,218262.0,01/06/2025,New,organic,...,Blinkit10,Percentage,No,Yes,NaN,4,26/03/2022,Active,0,NaN
121198,CUST023516,Subhajit Rao,subhajitrao9566@gmail.com,+91-8690648044,Chennai,Tamil Nadu,734308.0,04/11/2022,Occasional,Influencer,...,NONE,NaN,No,Yes,10.0,6,05/12/2022,Active,0,NaN
121199,CUST005654,Anirban Iyer,anirbaniyer3697@gmail.com,+91-7823805399,Mumbai,Maharashtra,425777.0,NaN,New,Push Notification,...,NONE,NaN,No,Yes,2.0,9,23/06/2021,Active,0,NaN

In [5]:
# Basic understanding of the dataset
df.shape

(121200, 41)

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 121200 entries, 0 to 121199
Data columns (total 41 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   customer_id                121200 non-null  str
 1   customer_name              121200 non-null  str
 2   email                      119704 non-null  str
 3   phone                      120208 non-null  str
 4   city                       121200 non-null  str
 5   state                      121200 non-null  str
 6   pincode                    119999 non-null  float64
 7   signup_date                47684 non-null   str
 8   customer_segment           119010 non-null  str
 9   acquisition_channel        119353 non-null  str
 10  device_type                121200 non-null  str
 11  order_id                   121200 non-null  str
 12  order_date                 47569 non-null   str
 13  order_time                 47569 non-null   str
 14  order_status               121200 non-null  str
 15  cancel_reason              8475 non-null    str
 16  product_id                 121200 non-null  str
 17  product_name               121200 non-null  str
 18  category                   121200 non-null  str
 19  sub_category               121200 non-null  str
 20  quantity                   121200 non-null  int64
 21  unit_price                 121200 non-null  float64
 22  gross_amount               121200 non-null  float64
 23  discount_amount            121200 non-null  float64
 24  delivery_fee               121200 non-null  int64
 25  final_amount               121200 non-null  float64
 26  payment_method             119745 non-null  str
 27  payment_status             121200 non-null  str
 28  delivery_time_minutes      110298 non-null  float64
 29  delivery_rating            101482 non-null  float64
 30  order_rating               103555 non-null  float64
 31  coupon_code                118238 non-null  str
 32  coupon_type                70148 non-null   str
 33  first_order_flag           121200 non-null  str
 34  repeat_order_flag          121200 non-null  str
 35  days_since_previous_order  103075 non-null  float64
 36  app_session_count          121200 non-null  int64
 37  last_login_date            118157 non-null  str
 38  customer_status            121200 non-null  str
 39  churn_flag                 121200 non-null  int64
 40  churn_date                 4088 non-null    str
dtypes: float64(9), int64(4), str(28)
memory usage: 61.7 MB

In [10]:
# Check the data types of each column

df.dtypes

customer_id                      str
customer_name                    str
email                            str
phone                            str
city                             str
state                            str
pincode                      float64
signup_date                      str
customer_segment                 str
acquisition_channel              str
device_type                      str
order_id                         str
order_date                       str
order_time                       str
order_status                     str
cancel_reason                    str
product_id                       str
product_name                     str
category                         str
sub_category                     str
quantity                       int64
unit_price                   float64
gross_amount                 float64
discount_amount              float64
delivery_fee                   int64
final_amount                 float64
payment_method                   str
payment_status                   str
delivery_time_minutes        float64
delivery_rating              float64
order_rating                 float64
coupon_code                      str
coupon_type                      str
first_order_flag                 str
repeat_order_flag                str
days_since_previous_order    float64
app_session_count              int64
last_login_date                  str
customer_status                  str
churn_flag                     int64
churn_date                       str
dtype: object

In [11]:
# Check missing values

df.isnull().sum()

customer_id                       0
customer_name                     0
email                          1496
phone                           992
city                              0
state                             0
pincode                        1201
signup_date                   73516
customer_segment               2190
acquisition_channel            1847
device_type                       0
order_id                          0
order_date                    73631
order_time                    73631
order_status                      0
cancel_reason                112725
product_id                        0
product_name                      0
category                          0
sub_category                      0
quantity                          0
unit_price                        0
gross_amount                      0
discount_amount                   0
delivery_fee                      0
final_amount                      0
payment_method                 1455
payment_status                    0
delivery_time_minutes         10902
delivery_rating               19718
order_rating                  17645
coupon_code                    2962
coupon_type                   51052
first_order_flag                  0
repeat_order_flag                 0
days_since_previous_order     18125
app_session_count                 0
last_login_date                3043
customer_status                   0
churn_flag                        0
churn_date                   117112
dtype: int64

In [7]:
# Clean the column names
df.columns = df.columns.str.strip().str.lower().str.replace(" ","_")

df.columns

Index(['customer_id', 'customer_name', 'email', 'phone', 'city', 'state',
       'pincode', 'signup_date', 'customer_segment', 'acquisition_channel',
       'device_type', 'order_id', 'order_date', 'order_time', 'order_status',
       'cancel_reason', 'product_id', 'product_name', 'category',
       'sub_category', 'quantity', 'unit_price', 'gross_amount',
       'discount_amount', 'delivery_fee', 'final_amount', 'payment_method',
       'payment_status', 'delivery_time_minutes', 'delivery_rating',
       'order_rating', 'coupon_code', 'coupon_type', 'first_order_flag',
       'repeat_order_flag', 'days_since_previous_order', 'app_session_count',
       'last_login_date', 'customer_status', 'churn_flag', 'churn_date'],
      dtype='str')

In [8]:
# Remove duplicates if esist

df= df.drop_duplicates()

In [9]:
# Check for duplicates

df.duplicated().sum()

np.int64(0)

In [10]:
# Clean text and category columns

text_columns = [
     "city",
     "state",
     "customer_segment",
     "acquisition_channel",
     "device_type",
     "order_status",
     "payment_method",
     "payment_status",
     "category",
]

for col in text_columns: df[col] = df[col].astype("string").str.strip()

In [11]:
# category value consistant

df["city"] = df["city"].str.title()
df["category"] = df["category"].str.title()
df["state"] = df["state"].str.title()

df["payment_method"] = df["payment_method"].replace({
    "UPI": "UPI",
    "upi": "UPI",
    "Credit Card": "Credit Card",
    "credit card": "Credit Card",
    "Debit Card": "Debit Card",
    "debit card": "Debit Card",
    "Net Banking": "Net Banking",
    "net banking": "Net Banking",
    "Cash on Delivery": "COD",
    "Cod": "COD"
})

In [16]:
# Date columns into proper datetime format

date_columns = [
    "signup_date",
    "order_date",
    "order_time",
    "last_login_date",
    "churn_date"
]

for col in date_columns: df[col] = pd.to_datetime(df[col],dayfirst=True, errors="coerce")

In [17]:
df[date_columns].dtypes

signup_date        datetime64[us]
order_date         datetime64[us]
order_time         datetime64[us]
last_login_date    datetime64[us]
churn_date         datetime64[us]
dtype: object

In [18]:
# check missing values

df.isnull().sum()

customer_id                       0
customer_name                     0
email                          1495
phone                           981
city                              0
state                             0
pincode                        1194
signup_date                   72831
customer_segment               2175
acquisition_channel            1830
device_type                       0
order_id                          0
order_date                    72924
order_time                    72924
order_status                      0
cancel_reason                111640
product_id                        0
product_name                      0
category                          0
sub_category                      0
quantity                          0
unit_price                        0
gross_amount                      0
discount_amount                   0
delivery_fee                      0
final_amount                      0
payment_method                 1449
payment_status                    0
delivery_time_minutes         10791
delivery_rating               19531
order_rating                  17471
coupon_code                    2935
coupon_type                   50536
first_order_flag                  0
repeat_order_flag                 0
days_since_previous_order     17940
app_session_count                 0
last_login_date                3026
customer_status                   0
churn_flag                        0
churn_date                   115984
dtype: int64

In [19]:
category_columns = [
    "customer_segment",
    "acquisition_channel",
    "payment_method",
    "cancel_reason"
]

for col in category_columns:
    df[col] = df[col].fillna("Unknown")

In [23]:
# fix numarical values

# fix numerical values
df.loc[df["quantity"] <= 0, "quantity"] = np.nan
df.loc[df["delivery_time_minutes"] < 0, "delivery_time_minutes"] = np.nan

In [26]:
df.loc[(df["order_rating"] < 1) | (df["order_rating"] >5), "order_rating"] =np.nan

In [27]:
# Final Check

df.shape

(120033, 41)

In [28]:
df.isnull().sum()

customer_id                       0
customer_name                     0
email                          1495
phone                           981
city                              0
state                             0
pincode                        1194
signup_date                   72831
customer_segment                  0
acquisition_channel               0
device_type                       0
order_id                          0
order_date                    72924
order_time                    72924
order_status                      0
cancel_reason                     0
product_id                        0
product_name                      0
category                          0
sub_category                      0
quantity                        205
unit_price                        0
gross_amount                      0
discount_amount                   0
delivery_fee                      0
final_amount                      0
payment_method                    0
payment_status                    0
delivery_time_minutes         10878
delivery_rating               19531
order_rating                  17471
coupon_code                    2935
coupon_type                   50536
first_order_flag                  0
repeat_order_flag                 0
days_since_previous_order     17940
app_session_count                 0
last_login_date                3026
customer_status                   0
churn_flag                        0
churn_date                   115984
dtype: int64

In [29]:
print(df.duplicated().sum())

0

In [30]:
df.info()

<class 'pandas.DataFrame'>
Index: 120033 entries, 0 to 121199
Data columns (total 41 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   customer_id                120033 non-null  str
 1   customer_name              120033 non-null  str
 2   email                      118538 non-null  str
 3   phone                      119052 non-null  str
 4   city                       120033 non-null  string
 5   state                      120033 non-null  string
 6   pincode                    118839 non-null  float64
 7   signup_date                47202 non-null   datetime64[us]
 8   customer_segment           120033 non-null  string
 9   acquisition_channel        120033 non-null  string
 10  device_type                120033 non-null  string
 11  order_id                   120033 non-null  str
 12  order_date                 47109 non-null   datetime64[us]
 13  order_time                 47109 non-null   datetime64[us]
 14  order_status               120033 non-null  string
 15  cancel_reason              120033 non-null  str
 16  product_id                 120033 non-null  str
 17  product_name               120033 non-null  str
 18  category                   120033 non-null  string
 19  sub_category               120033 non-null  str
 20  quantity                   119828 non-null  float64
 21  unit_price                 120033 non-null  float64
 22  gross_amount               120033 non-null  float64
 23  discount_amount            120033 non-null  float64
 24  delivery_fee               120033 non-null  int64
 25  final_amount               120033 non-null  float64
 26  payment_method             120033 non-null  string
 27  payment_status             120033 non-null  string
 28  delivery_time_minutes      109155 non-null  float64
 29  delivery_rating            100502 non-null  float64
 30  order_rating               102562 non-null  float64
 31  coupon_code                117098 non-null  str
 32  coupon_type                69497 non-null   str
 33  first_order_flag           120033 non-null  str
 34  repeat_order_flag          120033 non-null  str
 35  days_since_previous_order  102093 non-null  float64
 36  app_session_count          120033 non-null  int64
 37  last_login_date            117007 non-null  datetime64[us]
 38  customer_status            120033 non-null  str
 39  churn_flag                 120033 non-null  int64
 40  churn_date                 4049 non-null    datetime64[us]
dtypes: datetime64[us](5), float64(10), int64(3), str(14), string(9)
memory usage: 60.3 MB

In [31]:
df.head()

,customer_id,customer_name,email,phone,city,state,pincode,signup_date,customer_segment,acquisition_channel,...,coupon_code,coupon_type,first_order_flag,repeat_order_flag,days_since_previous_order,app_session_count,last_login_date,customer_status,churn_flag,churn_date
0,CUST021709,Rahul Bose,rahulbose8562@gmail.com,+91-9613303371,Noida,Uttar Pradesh,359716.0,NaT,New,Google,...,NONE,NaN,No,No,2.0,8,2023-08-04,Active,0,NaT
1,CUST000045,Kavya Das,kavyadas9226@gmail.com,+91-7718105707,Chennai,Tamil Nadu,543681.0,2023-06-03,Regular,Organic,...,NONE,NaN,Yes,No,5.0,9,2021-10-17,Active,0,NaT
2,CUST002107,Priya Bhowmik,priyabhowmik3537@gmail.com,+91-9931090623,Delhi,Delhi,621002.0,2023-03-02,New,Organic,...,WELCOME50,percentage,yes,No,1.0,1,2024-10-11,Churned,1,NaT
3,CUST006550,Rohan Mitra,rohanmitra6670@gmail.com,+91-8987626850,Pune,Maharashtra,901670.0,2021-05-11,new,Facebook,...,WELCOME50,Percentage,No,No,NaN,4,2021-05-11,Active,0,NaT
4,CUST015480,Diya Ganguly,diyaganguly3031@gmail.com,+91-9094700117,Jaipur,Rajasthan,984637.0,NaT,Regular,Organic,...,NONE,NaN,No,Yes,21.0,6,2025-06-13,Active,0,NaT

In [ ]:
import sqlite3

# Save the data

db_path = r"C:\Users\Sabuj Some\OneDrive\Documents\Personal\Projects\Blinkit Retention, Churn & Cohort Analytics\Cleaned Data\Cleaned_data.sql"

conn = sqlite3.connect(db_path)
df.to_sql("cleaned_data", conn, if_exists="replace", index=False)
conn.close()

TypeError: NDFrame.to_sql() missing 1 required positional argument: 'con'